/*
 * This file is generated by jOOQ.
 */
package com.smotana.clearflask.store.mysql.model;


import com.smotana.clearflask.store.mysql.model.tables.JooqAccount;
import com.smotana.clearflask.store.mysql.model.tables.JooqComment;
import com.smotana.clearflask.store.mysql.model.tables.JooqCommentParentId;
import com.smotana.clearflask.store.mysql.model.tables.JooqIdea;
import com.smotana.clearflask.store.mysql.model.tables.JooqIdeaFunders;
import com.smotana.clearflask.store.mysql.model.tables.JooqIdeaTags;
import com.smotana.clearflask.store.mysql.model.tables.JooqUser;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqTables {

    /**
     * The table <code>account</code>.
     */
    public static final JooqAccount ACCOUNT = JooqAccount.ACCOUNT;

    /**
     * The table <code>comment</code>.
     */
    public static final JooqComment COMMENT = JooqComment.COMMENT;

    /**
     * The table <code>comment_parent_id</code>.
     */
    public static final JooqCommentParentId COMMENT_PARENT_ID = JooqCommentParentId.COMMENT_PARENT_ID;

    /**
     * The table <code>idea</code>.
     */
    public static final JooqIdea IDEA = JooqIdea.IDEA;

    /**
     * The table <code>idea_funders</code>.
     */
    public static final JooqIdeaFunders IDEA_FUNDERS = JooqIdeaFunders.IDEA_FUNDERS;

    /**
     * The table <code>idea_tags</code>.
     */
    public static final JooqIdeaTags IDEA_TAGS = JooqIdeaTags.IDEA_TAGS;

    /**
     * The table <code>user</code>.
     */
    public static final JooqUser USER = JooqUser.USER;
}
