#!/bin/bash

set -ex

rsync -P ./clearflask-server/target/clearflask-server-0.1.war ec2-23-20-222-8.compute-1.amazonaws.com:~

ssh ec2-23-20-222-8.compute-1.amazonaws.com "set -x && sudo service tomcat stop && sudo cp /home/ec2-user/clearflask-server-0.1.war /var/lib/tomcat/webapps/ROOT.war && sudo service tomcat restart"


