/* tslint:disable */
/* tslint:disable */
/**
 * ClearFlask Connect API
 * ClearFlask API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
// eslint-disable-next-line no-unused-vars
import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface Challenge
 */
export interface Challenge {
    /**
     * 
     * @type {string}
     * @memberof Challenge
     */
    result: string;
}

export function ChallengeFromJSON(json: any): Challenge {
    return {
        'result': json['result'],
    };
}

export function ChallengeToJSON(value?: Challenge): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'result': value.result,
    };
}


