/* tslint:disable */
/* tslint:disable */
/**
 * ClearFlask Connect API
 * ClearFlask API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
// eslint-disable-next-line no-unused-vars
import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface Keypair
 */
export interface Keypair {
    /**
     * 
     * @type {string}
     * @memberof Keypair
     */
    privateKeyPem: string;
    /**
     * 
     * @type {string}
     * @memberof Keypair
     */
    privateKeyJwkJson: string;
}

export function KeypairFromJSON(json: any): Keypair {
    return {
        'privateKeyPem': json['privateKeyPem'],
        'privateKeyJwkJson': json['privateKeyJwkJson'],
    };
}

export function KeypairToJSON(value?: Keypair): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'privateKeyPem': value.privateKeyPem,
        'privateKeyJwkJson': value.privateKeyJwkJson,
    };
}


