/*
 * This file is generated by jOOQ.
 */
package com.smotana.clearflask.store.mysql.model.tables.records;


import com.smotana.clearflask.store.mysql.model.tables.JooqAccount;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;
import java.time.Instant;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "https://www.jooq.org",
                "jOOQ version:3.16.10"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class JooqAccountRecord extends UpdatableRecordImpl<JooqAccountRecord> implements Record6<String, String, String, String, String, Instant> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>account.accountId</code>.
     */
    public void setAccountid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>account.accountId</code>.
     */
    public String getAccountid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>account.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>account.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>account.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>account.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>account.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>account.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>account.planid</code>.
     */
    public void setPlanid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>account.planid</code>.
     */
    public String getPlanid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>account.created</code>.
     */
    public void setCreated(Instant value) {
        set(5, value);
    }

    /**
     * Getter for <code>account.created</code>.
     */
    public Instant getCreated() {
        return (Instant) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, String, String, Instant> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, String, String, String, Instant> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JooqAccount.ACCOUNT.ACCOUNTID;
    }

    @Override
    public Field<String> field2() {
        return JooqAccount.ACCOUNT.NAME;
    }

    @Override
    public Field<String> field3() {
        return JooqAccount.ACCOUNT.EMAIL;
    }

    @Override
    public Field<String> field4() {
        return JooqAccount.ACCOUNT.STATUS;
    }

    @Override
    public Field<String> field5() {
        return JooqAccount.ACCOUNT.PLANID;
    }

    @Override
    public Field<Instant> field6() {
        return JooqAccount.ACCOUNT.CREATED;
    }

    @Override
    public String component1() {
        return getAccountid();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public String component4() {
        return getStatus();
    }

    @Override
    public String component5() {
        return getPlanid();
    }

    @Override
    public Instant component6() {
        return getCreated();
    }

    @Override
    public String value1() {
        return getAccountid();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public String value4() {
        return getStatus();
    }

    @Override
    public String value5() {
        return getPlanid();
    }

    @Override
    public Instant value6() {
        return getCreated();
    }

    @Override
    public JooqAccountRecord value1(String value) {
        setAccountid(value);
        return this;
    }

    @Override
    public JooqAccountRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public JooqAccountRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public JooqAccountRecord value4(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public JooqAccountRecord value5(String value) {
        setPlanid(value);
        return this;
    }

    @Override
    public JooqAccountRecord value6(Instant value) {
        setCreated(value);
        return this;
    }

    @Override
    public JooqAccountRecord values(String value1, String value2, String value3, String value4, String value5, Instant value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqAccountRecord
     */
    public JooqAccountRecord() {
        super(JooqAccount.ACCOUNT);
    }

    /**
     * Create a detached, initialised JooqAccountRecord
     */
    public JooqAccountRecord(String accountid, String name, String email, String status, String planid, Instant created) {
        super(JooqAccount.ACCOUNT);

        setAccountid(accountid);
        setName(name);
        setEmail(email);
        setStatus(status);
        setPlanid(planid);
        setCreated(created);
    }
}
