/*
 * This file is generated by jOOQ.
 */
package com.smotana.clearflask.store.mysql.model.tables.records;


import com.smotana.clearflask.store.mysql.model.tables.JooqIdeaTags;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqIdeaTagsRecord extends UpdatableRecordImpl<JooqIdeaTagsRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>idea_tags.projectId</code>.
     */
    public void setProjectid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>idea_tags.projectId</code>.
     */
    public String getProjectid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>idea_tags.postId</code>.
     */
    public void setPostid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>idea_tags.postId</code>.
     */
    public String getPostid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>idea_tags.tagId</code>.
     */
    public void setTagid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>idea_tags.tagId</code>.
     */
    public String getTagid() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JooqIdeaTags.IDEA_TAGS.PROJECTID;
    }

    @Override
    public Field<String> field2() {
        return JooqIdeaTags.IDEA_TAGS.POSTID;
    }

    @Override
    public Field<String> field3() {
        return JooqIdeaTags.IDEA_TAGS.TAGID;
    }

    @Override
    public String component1() {
        return getProjectid();
    }

    @Override
    public String component2() {
        return getPostid();
    }

    @Override
    public String component3() {
        return getTagid();
    }

    @Override
    public String value1() {
        return getProjectid();
    }

    @Override
    public String value2() {
        return getPostid();
    }

    @Override
    public String value3() {
        return getTagid();
    }

    @Override
    public JooqIdeaTagsRecord value1(String value) {
        setProjectid(value);
        return this;
    }

    @Override
    public JooqIdeaTagsRecord value2(String value) {
        setPostid(value);
        return this;
    }

    @Override
    public JooqIdeaTagsRecord value3(String value) {
        setTagid(value);
        return this;
    }

    @Override
    public JooqIdeaTagsRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqIdeaTagsRecord
     */
    public JooqIdeaTagsRecord() {
        super(JooqIdeaTags.IDEA_TAGS);
    }

    /**
     * Create a detached, initialised JooqIdeaTagsRecord
     */
    public JooqIdeaTagsRecord(String projectid, String postid, String tagid) {
        super(JooqIdeaTags.IDEA_TAGS);

        setProjectid(projectid);
        setPostid(postid);
        setTagid(tagid);
    }
}
