/*
 * This file is generated by jOOQ.
 */
package com.smotana.clearflask.store.mysql.model.tables.records;


import com.smotana.clearflask.store.mysql.model.tables.JooqIdeaFunders;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.10"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqIdeaFundersRecord extends UpdatableRecordImpl<JooqIdeaFundersRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>idea_funders.projectId</code>.
     */
    public void setProjectid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>idea_funders.projectId</code>.
     */
    public String getProjectid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>idea_funders.postId</code>.
     */
    public void setPostid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>idea_funders.postId</code>.
     */
    public String getPostid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>idea_funders.funderUserId</code>.
     */
    public void setFunderuserid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>idea_funders.funderUserId</code>.
     */
    public String getFunderuserid() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JooqIdeaFunders.IDEA_FUNDERS.PROJECTID;
    }

    @Override
    public Field<String> field2() {
        return JooqIdeaFunders.IDEA_FUNDERS.POSTID;
    }

    @Override
    public Field<String> field3() {
        return JooqIdeaFunders.IDEA_FUNDERS.FUNDERUSERID;
    }

    @Override
    public String component1() {
        return getProjectid();
    }

    @Override
    public String component2() {
        return getPostid();
    }

    @Override
    public String component3() {
        return getFunderuserid();
    }

    @Override
    public String value1() {
        return getProjectid();
    }

    @Override
    public String value2() {
        return getPostid();
    }

    @Override
    public String value3() {
        return getFunderuserid();
    }

    @Override
    public JooqIdeaFundersRecord value1(String value) {
        setProjectid(value);
        return this;
    }

    @Override
    public JooqIdeaFundersRecord value2(String value) {
        setPostid(value);
        return this;
    }

    @Override
    public JooqIdeaFundersRecord value3(String value) {
        setFunderuserid(value);
        return this;
    }

    @Override
    public JooqIdeaFundersRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqIdeaFundersRecord
     */
    public JooqIdeaFundersRecord() {
        super(JooqIdeaFunders.IDEA_FUNDERS);
    }

    /**
     * Create a detached, initialised JooqIdeaFundersRecord
     */
    public JooqIdeaFundersRecord(String projectid, String postid, String funderuserid) {
        super(JooqIdeaFunders.IDEA_FUNDERS);

        setProjectid(projectid);
        setPostid(postid);
        setFunderuserid(funderuserid);
    }
}
