/*
 * This file is generated by jOOQ.
 */
package com.smotana.clearflask.store.mysql.model.tables.records;


import com.smotana.clearflask.store.mysql.model.tables.JooqCommentParentId;
import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "https://www.jooq.org",
                "jOOQ version:3.16.10"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class JooqCommentParentIdRecord extends UpdatableRecordImpl<JooqCommentParentIdRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>comment_parent_id.projectId</code>.
     */
    public void setProjectid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>comment_parent_id.projectId</code>.
     */
    public String getProjectid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>comment_parent_id.postId</code>.
     */
    public void setPostid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>comment_parent_id.postId</code>.
     */
    public String getPostid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>comment_parent_id.commentId</code>.
     */
    public void setCommentid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>comment_parent_id.commentId</code>.
     */
    public String getCommentid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>comment_parent_id.parentCommentId</code>.
     */
    public void setParentcommentid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>comment_parent_id.parentCommentId</code>.
     */
    public String getParentcommentid() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record4<String, String, String, String> key() {
        return (Record4) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JooqCommentParentId.COMMENT_PARENT_ID.PROJECTID;
    }

    @Override
    public Field<String> field2() {
        return JooqCommentParentId.COMMENT_PARENT_ID.POSTID;
    }

    @Override
    public Field<String> field3() {
        return JooqCommentParentId.COMMENT_PARENT_ID.COMMENTID;
    }

    @Override
    public Field<String> field4() {
        return JooqCommentParentId.COMMENT_PARENT_ID.PARENTCOMMENTID;
    }

    @Override
    public String component1() {
        return getProjectid();
    }

    @Override
    public String component2() {
        return getPostid();
    }

    @Override
    public String component3() {
        return getCommentid();
    }

    @Override
    public String component4() {
        return getParentcommentid();
    }

    @Override
    public String value1() {
        return getProjectid();
    }

    @Override
    public String value2() {
        return getPostid();
    }

    @Override
    public String value3() {
        return getCommentid();
    }

    @Override
    public String value4() {
        return getParentcommentid();
    }

    @Override
    public JooqCommentParentIdRecord value1(String value) {
        setProjectid(value);
        return this;
    }

    @Override
    public JooqCommentParentIdRecord value2(String value) {
        setPostid(value);
        return this;
    }

    @Override
    public JooqCommentParentIdRecord value3(String value) {
        setCommentid(value);
        return this;
    }

    @Override
    public JooqCommentParentIdRecord value4(String value) {
        setParentcommentid(value);
        return this;
    }

    @Override
    public JooqCommentParentIdRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqCommentParentIdRecord
     */
    public JooqCommentParentIdRecord() {
        super(JooqCommentParentId.COMMENT_PARENT_ID);
    }

    /**
     * Create a detached, initialised JooqCommentParentIdRecord
     */
    public JooqCommentParentIdRecord(String projectid, String postid, String commentid, String parentcommentid) {
        super(JooqCommentParentId.COMMENT_PARENT_ID);

        setProjectid(projectid);
        setPostid(postid);
        setCommentid(commentid);
        setParentcommentid(parentcommentid);
    }
}
