import greenlockExpress from 'greenlock-express';
import httpp from 'http-proxy';
import connectConfig from './config';
import httpx from './httpx';

// const reactRenderer = require('./react-renderer');
// const routes = ['/', '/page'];

/**
 * initialize the application and create the routes
 */
// const app = express();

/** 
 * "/path-in-out-routes-arr" should always serve our server rendered page;
 * otherwise, continue with next handlers 
 * 
 * TODO: for now, no SSR, just GreenLock
 */
// app.get('/*', reactRenderer.render(routes));

/**
 * Set the location of the static assets (ie the js bundle generated by webapck)
 */
// app.use(express.static(path.resolve(__dirname, '../build')))
// app.use(express.static(path.resolve(__dirname, '../public')))

/**
 * Since this is the last non-error-handling
 * middleware use()d, we assume 404, as nothing else
 * responded.
 * 
 * TODO: for now, no SSR, just GreenLock
 */
// app.use(reactRenderer.render(routes));

// app.listen(PORT, () => console.log(`Example app listening on port ${PORT}!`));


// Eventyually proxy things over:
// https://git.coolaj86.com/coolaj86/greenlock-express.js/src/branch/master/examples/http-proxy/server.js

greenlockExpress
  .init({
    agreeToTerms: true,
    renewOffset: "-45d",
    renewStagger: "15d",
    packageRoot: process.cwd(),
    configDir: './greenlock.d',
    packageAgent: 'clearflask/1.0',
    maintainerEmail: connectConfig.email,
    subscriberEmail: connectConfig.email,

    cluster: true,
    workers: 1,

    manager: {
      module: `${process.cwd()}/src/greenlock/greenlock-manager-clearflask.js`
    },
    store: {
      module: `${process.cwd()}/src/greenlock/greenlock-store-clearflask.js`
    },
    challenges: {
      "http-01": {
        module: `${process.cwd()}/src/greenlock/greenlock-challenge-http-clearflask.js`,
      },
    },

    notify: function (event, details) {
      console.log('EVENT:', event, details);
    },
  })
  .ready(worker)
  .master(function () {
    console.log('Master Started');
  });

// Proxy
const serverHttpp = httpp.createProxyServer({ xfwd: true });
serverHttpp.on("error", function (err, req, res) {
  console.error(err);
  res.statusCode = 500;
  res.end();
  return;
});

function worker(glx) {
  // Http
  // const serverHttp = glx.httpServer();
  const serverHttp = glx.httpServer(function (req, res) {
    res.statusCode = 301;
    res.setHeader("Location", `https://${connectConfig.externalDomain}`);
    res.end("Redirecting...");
  });

  // Https
  const serverHttps = glx.httpsServer();
  // const serverHttps = glx.httpsServer((req, res) => {
  //   res.statusCode = 200;
  //   res.end('Hello, Encrypted World!');
  // });
  serverHttps.on("upgrade", function (req, socket, head) {
    serverHttpp.ws(req, socket, head, {
      ws: true,
      target: "ws://localhost:8080"
    });
  });

  // Http(s)
  const serverHttpx = httpx.createServer(serverHttp, serverHttps);
  serverHttpx.listen(connectConfig.listenPort, () => console.log(`Listening on port ${connectConfig.listenPort}!`));

  // App
  glx.serveApp(function (req, res) {
    serverHttpp.web(req, res, {
      target: "http://localhost:8080"
    });
  });
  // serverHttp.listen(80);
  // serverHttps.listen(443);
}
