/* tslint:disable */
/* tslint:disable */
/**
 * ClearFlask Connect API
 * ClearFlask API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
// eslint-disable-next-line no-unused-vars
import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface Cert
 */
export interface Cert {
    /**
     * 
     * @type {string}
     * @memberof Cert
     */
    cert: string;
    /**
     * 
     * @type {string}
     * @memberof Cert
     */
    chain: string;
    /**
     * 
     * @type {string}
     * @memberof Cert
     */
    subject: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Cert
     */
    altnames: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof Cert
     */
    issuedAt: number;
    /**
     * 
     * @type {number}
     * @memberof Cert
     */
    expiresAt: number;
}

export function CertFromJSON(json: any): Cert {
    return {
        'cert': json['cert'],
        'chain': json['chain'],
        'subject': json['subject'],
        'altnames': json['altnames'],
        'issuedAt': json['issuedAt'],
        'expiresAt': json['expiresAt'],
    };
}

export function CertToJSON(value?: Cert): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'cert': value.cert,
        'chain': value.chain,
        'subject': value.subject,
        'altnames': value.altnames,
        'issuedAt': value.issuedAt,
        'expiresAt': value.expiresAt,
    };
}


